modLoader = "javafml"
loaderVersion = "[4,)"
license = "Polyform-Shield-1.0.0"

[[mods]]
modId = "vulkanium"

version = "${version}"
displayName = "Vulkanium"

logoFile = "vulkanium-icon.png" #optional

authors = "JellySquid (jellysquid3), IMS212"

credits = "bytzo, PepperCode1, FlashyReese, altrisi, Grayray75, Madis0, Johni0702, comp500, coderbot16, Moulberry, MCRcortex, Altirix, embeddedt, pajicadvance, Kroppeb, douira, burgerindividual, TwistedZero, Leo40Git, haykam821, muzikbike"

description = '''
Vulkanium is a fork of Sodium, a powerful rendering engine for Minecraft which improves frame rates and reduces lag spikes.
'''

provides = ["indium"]

[modproperties.vulkanium]
"fabric-renderer-api-v1:contains_renderer" = true

[[mixins]]
config = "vulkanium-common.mixins.json"

[[mixins]]
config = "vulkanium-neoforge.mixins.json"